### ISSUE TITLE
[Help Wanted] How to use WasiConfig.PreopenDir?

### ISSUE THREAD

**Issue by Superice666** [kawamuray/wasmtime-java#9]
I tried to pass a preopendir to wasi, but whatever the paths are, I get the same error:

java.lang.RuntimeException: java.lang.RuntimeException: IO error: 拒绝访问。 (os error 5)
Caused by: java.lang.RuntimeException: IO error: 拒绝访问。 (os error 5)
        at io.github.kawamuray.wasmtime.wasi.Wasi.newWasi(Native Method) ~[WebassemblyBN.jar:?]
        at io.github.kawamuray.wasmtime.wasi.Wasi.<init>(Wasi.java:18) ~[WebassemblyBN.jar:?]
        at com.blocklynukkit.loader.scriptloader.scriptengines.WasmScriptEngine.buildWasi(WasmScriptEngine.java:84) ~[BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.scriptloader.scriptengines.WasmScriptEngine.<init>(WasmScriptEngine.java:62) ~[BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.scriptloader.WasmLoader.putWasmEngine(WasmLoader.java:85) ~[BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.scriptloader.WasmLoader.loadplugins(WasmLoader.java:34) ~[BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.Loader.onEnable(Loader.java:250) ~[BlocklyNukkit.jar:1.7.25]
        ... 4 more

```[java]
private void buildWasi(){
    wasiConfig = new WasiConfig(new String[]{},new WasiConfig.PreopenDir[]{
            new WasiConfig.PreopenDir("./","/root");
    });
    wasi = new Wasi(store,wasiConfig);
    wasi.addToLinker(linker);
}
```
What should I do? Is it only happens on Windows? Any help would be appreciated!

**Comment by kawamuray** [comment]
I guess the error is related to filesystem permission?
I could imagine two possible causes:

1. Your application really doesn't have permission to the target directory. 
2. The filesystem path `"./"` is not valid on windows platform. As I previously wrote [here](https://github.com/kawamuray/wasmtime-java/issues/1#issuecomment-743691513), java automatically converts unix-style path to platform specific path when dealing with filesystems, but it is not the case for the `PreopenDir.hostPath` because, 1. it is a type of String and 2. the actual processing of the path (filesystem open) happens at Rust code, so we don't expect implicit path conversion performed here.

**Comment by kawamuray** [comment]
FYI, here's some example code and blog entry that I've done previously and know it works (on unix platform):
* https://engineering.linecorp.com/en/blog/adding-experimental-webassembly-support-to-decaton-part-1/
* https://github.com/kawamuray/decaton/blob/97d770bac6b062c8a18627a8b74487527f243bed/wasmton/src/main/java/com/linecorp/decaton/wasmton/WasmtonProcessor.java#L54

**Comment by Superice666** [comment]
Thanks a lot! Let me see.

**Comment by Superice666** [comment]
Solved, close.
